#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
source $HOME/.aliases
source <(kubectl completion zsh)

# Set color scheme to .dircolors
eval "$(dircolors ~/.dircolors)";
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

export VISUAL=vim
export EDITOR=vim

# Add Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Dotnet cli settings
export PATH="$PATH:$HOME/.dotnet/tools"
export DOTNET_CLI_TELEMETRY_OPTOUT=1

cd ~

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
